export const menuData = [
  {
    id: '1',
    icon: 'home',
    name: '首页',
    route: '/home',
  },
  {
    id: '2',
    icon: 'radius-setting',
    name: '系统管理',
    bpid: '1',
    route: '/system'
  },
  {
    id: '21',
    bpid: '2',
    mpid: '2',
    name: '项目管理',
    route: '/system/project',
  },
  {
    id: '22',
    bpid: '2',
    mpid: '2',
    name: '权限管理',
    route: '/system/permission',
  },
  {
    id: '23',
    bpid: '2',
    mpid: '2',
    name: '用户管理',
    route: '/system/user',
  },
  {
    id: '3',
    bpid: '1',
    icon: 'project',
    name: '项目部管理',
    route: '/project',
  },
  {
    id: '31',
    bpid: '3',
    mpid: '3',
    name: '工程项目信息卡',
    route: '/project/infoCard',
  },
  {
    id: '4',
    bpid: '1',
    icon: 'up-square',
    name: '对上计量管理',
    route: '/meteringUp',
  },
  {
    id: '5',
    bpid: '1',
    icon: 'schedule',
    name: '分包商管理',
    route: '/sub',
  },
  {
    id: '6',
    bpid: '1',
    icon: 'down-square',
    name: '对下管理',
    route: '/meteringDown',
  },
  {
    id: '7',
    bpid: '1',
    icon: 'team',
    name: '经管人员管理',
    route: '/manager',
  },
  {
    id: '8',
    bpid: '1',
    icon: 'file',
    name: '文档管理',
    route: '/files',
  },
]
